from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class FrontendStaticTests(unittest.TestCase):
    def test_canvas_supports_mobile_safari_touch_drag_tap_hint_and_pinch_zoom(self):
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn("touch-action: none", styles)
        self.assertIn("-webkit-touch-callout: none", styles)
        self.assertIn('canvas.addEventListener("pointerdown"', script)
        self.assertIn('canvas.addEventListener("touchstart"', script)
        self.assertIn("beginPinchZoom", script)
        self.assertIn("updatePinchZoom", script)
        self.assertIn("setZoom(pinchGesture.initialZoom", script)
        self.assertIn("showMobileNodeHint", script)
        self.assertIn("showContextMenu(node.slug", script)

    def test_mobile_tap_shows_tooltip_and_long_press_selects_without_menu(self):
        script = (ROOT / "public" / "app.js").read_text()
        pointer_up_start = script.index('window.addEventListener("pointerup"')
        pointer_up_end = script.index('window.addEventListener("pointercancel"', pointer_up_start)
        pointer_up_block = script[pointer_up_start:pointer_up_end]
        self.assertIn("showMobileNodeHint", pointer_up_block)
        self.assertIn("selectOnTap: !isTouchLike", pointer_up_block)

        long_press_start = script.index("longPressTimer = window.setTimeout")
        long_press_end = script.index("}, 580);", long_press_start)
        long_press_block = script[long_press_start:long_press_end]

        self.assertIn("selectMobileNode", long_press_block)
        self.assertIn("suppressContextMenuUntil", long_press_block)
        self.assertNotIn("showMobileNodeHint", long_press_block)
        self.assertNotIn("showContextMenu", long_press_block)

    def test_media_viewer_is_available_from_node_menu(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('data-action="media"', markup)
        self.assertIn('id="modalMedia"', markup)
        self.assertIn("/api/entity-media/", script)
        self.assertIn("renderMediaItems", script)

    def test_attach_file_uses_browser_file_picker(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('id="modalFileInput"', markup)
        self.assertIn('id="modalAttachDescription"', markup)
        self.assertIn('id="modalAttachStatus"', markup)
        self.assertIn('type="file"', markup)
        self.assertIn("new FormData()", script)
        self.assertIn('formData.append("file"', script)
        self.assertIn('formData.append("description"', script)
        self.assertIn("apiPostForm", script)
        self.assertIn('modalPrimaryButton.textContent = "Uploading..."', script)
        self.assertIn("modalFileInput.disabled = true", script)
        self.assertIn("modalAttachDescription.disabled = true", script)
        self.assertIn('throw new Error("Choose a file before attaching.")', script)

    def test_view_uses_rendered_markdown_modal(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertLess(markup.index('data-action="view"'), markup.index('data-action="timeline-view"'))
        self.assertLess(markup.index('data-action="timeline-view"'), markup.index('data-action="ask"'))
        self.assertLess(markup.index('data-action="remove-link"'), markup.index('data-action="backlinks"'))
        self.assertNotIn('data-action="edit">Modify markdown</button>', markup)
        self.assertNotIn('data-action="copy">Copy slug</button>', markup)
        self.assertIn('data-action="view">View</button>', markup)
        self.assertIn('id="modalMarkdown"', markup)
        self.assertIn("function renderMarkdownView", script)
        self.assertIn("renderMarkdownView(content)", script)
        self.assertIn("function renderViewModalMessage", script)
        self.assertIn('openNodeModal("edit", slug)', script)
        self.assertIn("modal-slug-inline", script)
        self.assertIn("inline-action-button", script)
        self.assertIn('modalKicker.textContent = action === "view" ? "View"', script)
        self.assertIn("data-entity-query", script)
        self.assertIn("searchEntityLink", script)
        self.assertIn("function createEntityMarkdownLink", script)
        self.assertIn("bracketSlug", script)
        self.assertIn(r"[^\]\s/]+(?:\/[^\]\s/]+)+", script)
        self.assertNotIn("[A-Za-z0-9][A-Za-z0-9._-]*", script)
        self.assertIn("function cleanMarkdownDestination", script)
        self.assertIn("function localFileUrlFromPath", script)
        self.assertIn("appendLocalFileLink", script)
        self.assertIn("appendLocalFileLink(parent, code)", script)
        self.assertIn('return `file://${encoded}`', script)
        self.assertIn("link.href = href", script)
        self.assertIn('link.target = "_blank"', script)
        self.assertIn("window.location.hostname", script)
        self.assertIn("function markdownTitleFromContent", script)
        self.assertIn("document.title = viewTitle", script)
        self.assertIn("modalTitle.textContent = viewTitle", script)
        self.assertIn("map(encodeURIComponent)", script)
        self.assertIn('value.startsWith("gbrain:files/")', script)
        self.assertIn('value.slice("gbrain:files/".length)', script)
        self.assertIn('document.createElement("strong")', script)
        self.assertIn('document.createElement("em")', script)
        self.assertIn('document.createElement("blockquote")', script)
        self.assertIn('document.createElement("table")', script)

    def test_ask_gbrain_uses_chat_modal(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('id="modalChat"', markup)
        self.assertIn('id="modalChatLog"', markup)
        self.assertIn('id="modalChatInput"', markup)
        self.assertIn("askChats: new Map()", script)
        self.assertIn("function renderAskChat", script)
        self.assertIn('modalPrimaryButton.textContent = "Send"', script)
        self.assertIn("history.push({ role: \"user\", content: question })", script)
        self.assertIn("history[history.length - 1]", script)

    def test_timeline_uses_read_only_markdown_with_add_event_button(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('data-action="timeline-view">Timeline</button>', markup)
        self.assertIn('id="timelineBadge"', markup)
        self.assertIn("timeline-badge", styles)
        self.assertIn('/api/entity-timeline-view/', script)
        self.assertIn("function refreshTimelineBadge", script)
        self.assertIn("function renderTimelineEventForm", script)
        self.assertIn("timelineOutputHasEntries", script)
        self.assertIn("operationTimelineDate", script)
        self.assertIn("operationTimelineSummary", script)
        self.assertIn("operationTimelineDetail", script)
        self.assertIn("operationTimelineSource", script)
        self.assertIn('openNodeModal("timeline-view", slug)', script)
        self.assertIn('modalKicker.textContent = "Timeline"', script)
        self.assertIn('modalPrimaryButton.textContent = "Add timeline event"', script)
        self.assertIn('modalCancelButton.textContent = "Close"', script)
        self.assertIn('renderMarkdownView(response.data.output || "(No timeline entries)")', script)
        self.assertIn('await openNodeModal("timeline", slug)', script)
        self.assertIn('await openNodeModal("timeline-view", slug)', script)

    def test_node_operations_use_guided_controls(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="modalForm"', markup)
        self.assertIn("function renderTagOperationForm", script)
        self.assertIn("Existing tags to add", script)
        self.assertIn("Applied tags to remove", script)
        self.assertIn("operationNewTag", script)
        self.assertIn("function renderAddRelationshipForm", script)
        self.assertIn("operationTargetOptions", script)
        self.assertIn("operationLinkTypeOptions", script)
        self.assertIn("function renderRemoveRelationshipForm", script)
        self.assertIn("operationExistingRelationshipOptions", script)
        self.assertIn("Choose one of the existing relationships from the list.", script)
        self.assertIn("function renderGraphQueryForm", script)
        self.assertIn("operationGraphLinkType", script)
        self.assertIn("operationGraphDirection", script)
        self.assertIn("operationGraphDepth", script)
        self.assertIn("Choose a depth from 1 to 3.", script)
        self.assertIn("operation-summary", styles)
        self.assertIn("compact-modal", styles)
        self.assertIn('["add-link", "remove-link", "tags"].includes(action)', script)
        self.assertIn("opacity: 0.75", styles)

    def test_new_node_button_uses_guided_create_form(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="newNodeButton"', markup)
        self.assertIn('class="new-node-floating"', markup)
        self.assertIn('id="newNodeButton" class="new-node-icon-button has-tooltip" type="button"', markup)
        self.assertIn('class="timeline-strip" aria-label="Graph time and tour controls"', markup)
        self.assertLess(markup.index('id="tourButton"'), markup.index('id="newNodeButton"'))
        self.assertIn("new-node-icon-button", styles)
        self.assertIn('openNodeModal("new-node", "")', script)
        self.assertIn("function renderNewNodeForm", script)
        self.assertIn("operationNodeName", script)
        self.assertIn("operationNodeDescription", script)
        self.assertIn("operationNodeCategoryOptions", script)
        self.assertIn('/api/entity-create', script)

    def test_star_map_cluster_lod_timeline_and_tour_controls(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertNotIn('class="hero-band"', markup)
        self.assertIn('class="metrics graph-stats-overlay graph-metrics-corner"', markup)
        self.assertIn('class="graph-canvas-wrap"', markup)
        self.assertGreater(markup.index('class="metrics graph-stats-overlay graph-metrics-corner"'), markup.index('class="graph-canvas-wrap"'))
        self.assertLess(markup.index('class="brand-wordmark-link"'), markup.index('class="header-workflow"'))
        self.assertLess(markup.index('id="sourceWarnings"'), markup.index('id="refreshButton"'))
        self.assertLess(markup.index('id="searchInput"'), markup.index('id="cloudModeToggle"'))
        self.assertLess(markup.index('id="timelineDaysInput"'), markup.index('id="timelineValue"'))
        self.assertIn('class="header-workflow" aria-label="Search and memory tour controls"', markup)
        self.assertIn("graph-floating-controls", markup)
        self.assertIn("cluster-icon-button", markup)
        self.assertIn('id="cloudModeButton"', markup)
        self.assertIn('id="historyBackButton"', markup)
        self.assertIn('id="historyForwardButton"', markup)
        self.assertIn('id="floatingHistoryBackButton"', markup)
        self.assertIn('id="floatingHistoryForwardButton"', markup)
        self.assertNotIn('Clustering On', markup)
        self.assertIn('id="timelineDaysInput"', markup)
        self.assertIn('type="number" min="0" max="7"', markup)
        self.assertIn('id="tourButton"', markup)
        self.assertNotIn('id="metricCollapsed"', markup)
        self.assertIn('id="hubClusterLegend"', markup)
        self.assertIn('id="categoryLimitInput"', markup)
        self.assertIn('id="clusterLimitInput"', markup)
        self.assertIn('<p class="panel-label">Category</p>', markup)
        self.assertIn('<p class="panel-label">Clusters</p>', markup)
        self.assertNotIn('<p class="panel-label">View Options</p>', markup)
        self.assertNotIn('id="detailLinks"', markup)
        self.assertNotIn('Direct links', markup)
        self.assertIn(".graph-stats-overlay", styles)
        self.assertIn(".graph-metrics-corner", styles)
        self.assertIn(".source-control-stack", styles)
        self.assertIn(".stat-toggle", styles)
        self.assertIn(".timeline-strip", styles)
        self.assertIn(".category-legend button.is-dimmed", styles)
        self.assertIn("hiddenClusters: new Set()", script)
        self.assertIn("hiddenHubConnections: new Set()", script)
        self.assertIn("function updateHubClusterLegend", script)
        self.assertIn("function isHiddenByHubConnection", script)
        self.assertIn("function buildTourSlugs", script)
        self.assertIn("function visibleTopHubs", script)
        self.assertIn("function passesTimeline", script)
        self.assertIn("function drawClusterClouds", script)
        self.assertIn("function degreeIntensity", script)
        self.assertIn("selectionHistory: { slugs: [], index: -1, navigating: false }", script)
        self.assertIn("function navigateSelectionHistory", script)
        self.assertIn("recordSelectionHistory(entity.slug)", script)
        self.assertIn("const categorySlots = new Map()", script)
        self.assertIn("hubGlow", script)
        self.assertIn("edgeLayer", script)
        self.assertIn("Click to hide this cluster", script)

    def test_top_search_and_filter_band_is_compact_and_category_based(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertNotIn("Search entities", markup)
        self.assertNotIn("Constellation View", markup)
        self.assertIn('rel="icon" type="image/png" href="/assets/brand/logo-circle-transparent.png"', markup)
        self.assertIn('rel="apple-touch-icon" href="/assets/brand/logo-circle-transparent.png"', markup)
        self.assertIn('class="brand-logo"', markup)
        self.assertIn('class="brand-wordmark"', markup)
        self.assertIn('class="brand-wordmark-link"', markup)
        self.assertIn('src="/assets/brand/wordmark-line-small.png"', markup)
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "logo-circle-transparent.png").exists())
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "wordmark-line.png").exists())
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "wordmark-line-small.png").exists())
        self.assertIn('href="https://github.com/techtony2018/memory-stargraph"', markup)
        self.assertIn("Matches", markup)
        self.assertIn(">Links</span>", markup)
        self.assertNotIn('id="categoryFilter"', markup)
        self.assertNotIn('id="clearFiltersButton"', markup)
        self.assertNotIn('id="tagFilter"', markup)
        self.assertNotIn('id="typeFilter"', markup)
        self.assertIn("has-tooltip", markup)
        self.assertIn(".has-tooltip::before", styles)
        self.assertIn("top: calc(100% + 8px)", styles)
        self.assertNotIn('class="search-wrap has-tooltip"', markup)
        self.assertNotIn("select-filter", styles)
        self.assertNotIn("list-filter", styles)
        self.assertNotIn("top-metrics", styles)
        self.assertIn("zoom-floating", styles)
        self.assertIn("zoom-icon-button", styles)
        self.assertIn("cluster-icon-button", styles)
        self.assertIn("left: 18px", styles)
        self.assertIn("top: 18px", styles)
        self.assertIn("flex-direction: row", styles)
        self.assertIn("opacity: 0.24", styles)
        self.assertIn("min-width: 252px", styles)
        self.assertIn("min-width: 76px", styles)
        self.assertIn("width: clamp(106px, 11vw, 126px)", styles)
        self.assertIn("zoom-level", styles)
        self.assertIn("z-index: 20", styles)
        self.assertIn("z-index: 50", styles)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(270px, 0.36fr)", styles)
        self.assertIn("resize: vertical", styles)
        self.assertIn("max-height: calc(1.65em * 5)", styles)
        self.assertNotIn("focused", markup)
        self.assertNotIn("neighborhood", markup)
        self.assertNotIn("search match", markup)
        self.assertIn("flex: 1 1 300px", styles)
        self.assertIn("min-width: 220px", styles)
        self.assertIn('href="/styles.css?v=1.0.75"', markup)
        self.assertIn('src="/app.js?v=1.0.75"', markup)
        self.assertIn('const UI_VERSION = "V1.0.75"', script)
        self.assertIn("height: 34px", styles)
        self.assertIn("align-items: center", styles)
        self.assertIn("filters: { minDegree: 0 }", script)
        self.assertNotIn("function renderCategoryFilter", script)
        self.assertNotIn("function renderMultiSelectFilter", script)
        self.assertNotIn("function updateMultiSelectFilter", script)
        self.assertNotIn("All Category", script)
        self.assertNotIn('"All Tags"', script)
        self.assertNotIn('value: "__untagged__"', script)
        self.assertNotIn("state.filters.tags", script)
        self.assertNotIn("state.filters.type", script)
        self.assertIn("zoomLevel", script)
        self.assertIn("updateCloudModeControl", script)
        self.assertNotIn("cloudModeButton.textContent", script)
        self.assertIn("displaySummary", script)
        self.assertIn('["summary", "metadata"].includes', script)

    def test_backlinks_modal_loads_immediately(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('modalMessage.textContent = "Loading backlinks..."', script)
        self.assertIn('modalEditor.value = "Loading backlinks..."', script)
        self.assertIn('apiPost(`/api/entity-backlinks/${encodeURIComponent(slug)}`, {})', script)
        self.assertIn("function renderBacklinksResult", script)
        self.assertIn("parseBacklinkRows", script)
        self.assertIn("data-backlink-slug", script)
        self.assertIn('fromLabel.textContent = "from_slug"', script)
        self.assertIn('linkBack.textContent = "Add relationship"', script)
        self.assertIn("openReverseRelationshipModal", script)
        self.assertIn('state.modalAction = { action: "result", slug, label }', script)
        self.assertNotIn('modalPrimaryButton.textContent = "Load backlinks"', script)

    def test_canvas_hint_adapts_to_pointer_type(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('(hover: hover) and (pointer: fine)', script)
        self.assertIn("Drag to rotate. Hover for full names. Click to select.", script)
        self.assertIn("Drag to rotate. Tap for full names. Long-press a node to select.", script)
        self.assertIn("hover for details, or click a node to select", script)
        self.assertIn("tap for details, or long-press a node to select", script)

    def test_search_normalization_preserves_unicode_terms(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn(r"[^\p{L}\p{N}]+", script)
        self.assertIn("toLocaleLowerCase()", script)
        self.assertIn("queryTerms.length > 0", script)
        self.assertNotIn(r"replace(/[^a-z0-9]+/g", script)


if __name__ == "__main__":
    unittest.main()
