from pathlib import Path
from html.parser import HTMLParser
import unittest


ROOT = Path(__file__).resolve().parents[1]


class ActionableControlParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.controls = []
        self._stack = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag in {"button", "a"} or attrs.get("role") == "button":
            self._stack.append({"tag": tag, "attrs": attrs, "text": []})
        elif self._stack:
            self._stack[-1]["text"].append(attrs.get("aria-label", ""))

    def handle_data(self, data):
        if self._stack:
            self._stack[-1]["text"].append(data)

    def handle_endtag(self, tag):
        if self._stack and self._stack[-1]["tag"] == tag:
            self.controls.append(self._stack.pop())


class FrontendStaticTests(unittest.TestCase):
    def test_canvas_supports_mobile_safari_touch_drag_tap_hint_and_pinch_zoom(self):
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn("touch-action: none", styles)
        self.assertIn("-webkit-touch-callout: none", styles)
        self.assertIn('canvas.addEventListener("pointerdown"', script)
        self.assertIn('canvas.addEventListener("touchstart"', script)
        self.assertIn("beginPinchZoom", script)
        self.assertIn("updatePinchZoom", script)
        self.assertIn("setZoom(pinchGesture.initialZoom", script)
        self.assertIn("showMobileNodeHint", script)
        self.assertIn("showContextMenu(node.slug", script)

    def test_mobile_tap_shows_tooltip_and_long_press_selects_without_menu(self):
        script = (ROOT / "public" / "app.js").read_text()
        pointer_up_start = script.index('window.addEventListener("pointerup"')
        pointer_up_end = script.index('window.addEventListener("pointercancel"', pointer_up_start)
        pointer_up_block = script[pointer_up_start:pointer_up_end]
        self.assertIn("showMobileNodeHint", pointer_up_block)
        self.assertIn("selectOnTap: !isTouchLike", pointer_up_block)

        long_press_start = script.index("longPressTimer = window.setTimeout")
        long_press_end = script.index("}, 580);", long_press_start)
        long_press_block = script[long_press_start:long_press_end]

        self.assertIn("selectMobileNode", long_press_block)
        self.assertIn("suppressContextMenuUntil", long_press_block)
        self.assertNotIn("showMobileNodeHint", long_press_block)
        self.assertNotIn("showContextMenu", long_press_block)

    def test_media_viewer_is_available_from_node_menu(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('data-action="media"', markup)
        self.assertIn('id="modalMedia"', markup)
        self.assertIn("/api/entity-media/", script)
        self.assertIn("renderMediaItems", script)

    def test_attach_file_uses_browser_file_picker(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('id="modalFileInput"', markup)
        self.assertIn('id="modalAttachDescription"', markup)
        self.assertIn('id="modalAttachStatus"', markup)
        self.assertIn('type="file"', markup)
        self.assertIn("new FormData()", script)
        self.assertIn('formData.append("file"', script)
        self.assertIn('formData.append("description"', script)
        self.assertIn("apiPostForm", script)
        self.assertIn('modalPrimaryButton.textContent = "Uploading..."', script)
        self.assertIn("modalFileInput.disabled = true", script)
        self.assertIn("modalAttachDescription.disabled = true", script)
        self.assertIn('throw new Error("Choose a file before attaching.")', script)

    def test_view_uses_rendered_markdown_modal(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertLess(markup.index('data-action="view"'), markup.index('data-action="ask-yoda"'))
        self.assertLess(markup.index('data-action="ask-yoda"'), markup.index('data-action="media"'))
        self.assertLess(markup.index('data-action="view-relationships"'), markup.index('data-action="backlinks"'))
        self.assertLess(markup.index('data-action="attach-file"'), markup.index('data-action="graph-query"'))
        self.assertLess(markup.index('data-action="graph-query"'), markup.index('data-action="timeline-view"'))
        self.assertLess(markup.index('data-action="timeline-view"'), markup.index('data-action="history"'))
        self.assertNotIn('data-action="add-link">Add relationship</button>', markup)
        self.assertNotIn('data-action="remove-link">Remove relationship</button>', markup)
        self.assertNotIn('data-action="edit">Modify markdown</button>', markup)
        self.assertNotIn('data-action="copy">Copy slug</button>', markup)
        self.assertNotIn('data-action="ask">Ask GBrain</button>', markup)
        self.assertIn('data-action="view">View</button>', markup)
        self.assertIn('id="modalMarkdown"', markup)
        self.assertIn("function renderMarkdownView", script)
        self.assertIn("renderMarkdownView(content)", script)
        self.assertIn("function renderViewModalMessage", script)
        self.assertIn('openNodeModal("edit", slug)', script)
        self.assertIn("modal-slug-inline", script)
        self.assertIn("inline-action-button", script)
        self.assertIn('modalKicker.textContent = action === "view" ? "View"', script)
        self.assertIn("data-entity-query", script)
        self.assertIn("searchEntityLink", script)
        self.assertIn("function createEntityMarkdownLink", script)
        self.assertIn("bracketSlug", script)
        self.assertIn(r"[^\]\s/]+(?:\/[^\]\s/]+)+", script)
        self.assertNotIn("[A-Za-z0-9][A-Za-z0-9._-]*", script)
        self.assertIn("function cleanMarkdownDestination", script)
        self.assertIn("function localFileUrlFromPath", script)
        self.assertIn("appendLocalFileLink", script)
        self.assertIn("appendLocalFileLink(parent, code)", script)
        self.assertIn('return localFileHrefForValue(cleaned)', script)
        self.assertIn('link.setAttribute("href", href)', script)
        self.assertIn('link.target = "_blank"', script)
        self.assertIn("window.location.hostname", script)
        self.assertIn("function markdownTitleFromContent", script)
        self.assertIn('document.title = "Memory Stargraph"', script)
        self.assertNotIn("document.title = viewTitle", script)
        self.assertIn("modalTitle.textContent = viewTitle", script)
        self.assertIn("map(encodeURIComponent)", script)
        self.assertIn('value.startsWith("gbrain:files/")', script)
        self.assertIn('value.slice("gbrain:files/".length)', script)
        self.assertIn('return `/media/${relativePath.replace', script)
        self.assertIn('document.createElement("strong")', script)
        self.assertIn('document.createElement("em")', script)
        self.assertIn('document.createElement("blockquote")', script)
        self.assertIn('document.createElement("table")', script)

    def test_ask_yoda_uses_markdown_chat_modal_with_timestamps_and_enter_send(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()

        self.assertIn('id="modalChat"', markup)
        self.assertIn('id="modalChatLog"', markup)
        self.assertIn('id="modalChatInput"', markup)
        self.assertNotIn("askChats: new Map()", script)
        self.assertIn("function renderAskChat", script)
        self.assertIn("function chatTimestamp", script)
        self.assertIn("chatTimestamp()", script)
        self.assertIn("renderMarkdownInline(message.content, bubble)", script)
        self.assertIn('modalChatInput.addEventListener("keydown"', script)
        self.assertIn('event.key === "Enter"', script)
        self.assertIn("!event.shiftKey", script)
        self.assertIn('modalPrimaryButton.textContent = "Send"', script)
        self.assertIn("history.push({ role: \"user\", content: question, timestamp: chatTimestamp() })", script)
        self.assertIn("history[history.length - 1]", script)

    def test_timeline_uses_read_only_markdown_with_add_event_button(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public" / "app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('data-action="timeline-view">Timeline</button>', markup)
        self.assertIn('id="timelineBadge"', markup)
        self.assertIn("timeline-badge", styles)
        self.assertIn('/api/entity-timeline-view/', script)
        self.assertIn("function refreshTimelineBadge", script)
        self.assertIn("function renderTimelineEventForm", script)
        self.assertIn("timelineOutputHasEntries", script)
        self.assertIn("operationTimelineDate", script)
        self.assertIn("operationTimelineSummary", script)
        self.assertIn("operationTimelineDetail", script)
        self.assertIn("operationTimelineSource", script)
        self.assertIn('openNodeModal("timeline-view", slug)', script)
        self.assertIn('modalKicker.textContent = "Timeline"', script)
        self.assertIn('modalPrimaryButton.textContent = "Add timeline event"', script)
        self.assertIn('modalCancelButton.textContent = "Close"', script)
        self.assertIn('renderMarkdownView(response.data.output || "(No timeline entries)")', script)
        self.assertIn('await openNodeModal("timeline", slug)', script)
        self.assertIn('await openNodeModal("timeline-view", slug)', script)

    def test_node_operations_use_guided_controls(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="modalForm"', markup)
        self.assertIn("function renderTagOperationForm", script)
        self.assertIn("Existing tags to add", script)
        self.assertIn("Applied tags to remove", script)
        self.assertIn("operationNewTag", script)
        self.assertIn("function renderAddRelationshipForm", script)
        self.assertIn("operationTargetPopup", script)
        self.assertIn('id: "operationLinkType"', script)
        self.assertIn('popup.id = `${id}Popup`', script)
        self.assertIn("function renderRemoveRelationshipForm", script)
        self.assertIn("operationExistingRelationshipOptions", script)
        self.assertIn("Choose one of the existing relationships from the list.", script)
        self.assertIn("function renderGraphQueryForm", script)
        self.assertIn("operationGraphLinkType", script)
        self.assertIn("operationGraphDirection", script)
        self.assertIn("operationGraphDepth", script)
        self.assertIn("Choose a depth from 1 to 3.", script)
        self.assertIn("operation-summary", styles)
        self.assertIn("compact-modal", styles)
        self.assertIn('["add-link", "remove-link", "tags"].includes(action)', script)
        self.assertIn("opacity: 0.75", styles)

    def test_new_node_button_uses_guided_create_form(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="newNodeButton"', markup)
        self.assertIn('class="new-node-floating"', markup)
        self.assertIn('id="newNodeButton" class="new-node-icon-button has-tooltip" type="button"', markup)
        self.assertIn('class="floating-tool-panel autopilot-flyout"', markup)
        self.assertLess(markup.index('id="tourButton"'), markup.index('id="newNodeButton"'))
        self.assertIn("new-node-icon-button", styles)
        self.assertIn('openNodeModal("new-node", "")', script)
        self.assertIn("function renderNewNodeForm", script)
        create_start = script.index('const creationNote = "node created via Memory Stargraph UI"')
        create_end = script.index('if (action === "delete")', create_start)
        create_block = script[create_start:create_end]
        self.assertIn("operationNodeName", script)
        self.assertIn("operationNodeDescription", script)
        self.assertIn("operationNodeCategoryOptions", script)
        self.assertIn('/api/entity-create', script)
        self.assertIn("node created via Memory Stargraph UI", create_block)
        self.assertIn("created via Memory Stargraph UI", create_block)
        self.assertIn("apiPost(\"/api/entity-create\", { name, description: creationDescription, category })", create_block)
        self.assertNotIn("source_slug", create_block)
        self.assertNotIn("context_slug", create_block)

    def test_star_map_cluster_lod_timeline_and_tour_controls(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertNotIn('class="hero-band"', markup)
        self.assertIn('class="radar-widget"', markup)
        self.assertIn('class="graph-canvas-wrap"', markup)
        self.assertGreater(markup.index('class="radar-widget"'), markup.index('class="graph-canvas-wrap"'))
        self.assertLess(markup.index('class="nav-rail"'), markup.index('class="graph-panel"'))
        self.assertLess(markup.index('id="sourceWarnings"'), markup.index('id="cacheLimitInput"'))
        self.assertLess(markup.index('id="searchInput"'), markup.index('id="cloudModeToggle"'))
        self.assertIn('id="tourPlanButton"', markup)
        self.assertLess(markup.index('id="autopilotModeIcon"'), markup.index('id="tourPlanButton"'))
        self.assertLess(markup.index('id="tourPlanButton"'), markup.index('id="tourButton"'))
        self.assertLess(markup.index('id="tourButton"'), markup.index('id="tourPrevButton"'))
        self.assertLess(markup.index('id="tourPrevButton"'), markup.index('id="tourNextButton"'))
        self.assertLess(markup.index('id="tourNextButton"'), markup.index('id="tourStopButton"'))
        self.assertNotIn("window.confirm(", script)
        self.assertIn('title.textContent = "Warning"', script)
        self.assertIn("plan-confirm-dialog", styles)
        self.assertIn('modalPrimaryButton.textContent = "Play"', script)
        self.assertNotIn('modalPrimaryButton.textContent = "OK"', script)
        self.assertIn("await startPlannedPlayback()", script)
        self.assertNotIn("fillPlanConfirming && !state.tour.useAutoList", script)
        self.assertIn('class="floating-tool-panel search-flyout"', markup)
        self.assertIn("graph-floating-controls", markup)
        self.assertIn("cluster-icon-button", markup)
        self.assertIn('id="cloudModeButton"', markup)
        self.assertIn('id="historyBackButton"', markup)
        self.assertIn('id="historyForwardButton"', markup)
        self.assertIn('id="floatingHistoryBackButton"', markup)
        self.assertIn('id="floatingHistoryForwardButton"', markup)
        self.assertNotIn('Clustering On', markup)
        self.assertNotIn('id="timelineDaysInput" type="number" min="0" max="7"', markup)
        self.assertIn('daysInput.id = "timelineDaysInput"', script)
        self.assertIn('id="tourButton"', markup)
        self.assertNotIn('id="metricCollapsed"', markup)
        self.assertIn('id="hubClusterLegend"', markup)
        self.assertIn('id="categoryLimitInput"', markup)
        self.assertIn('id="clusterLimitInput"', markup)
        self.assertIn('<p class="panel-label">Clusters</p>', markup)
        self.assertIn('<p class="panel-label">Hot Hubs</p>', markup)
        self.assertNotIn('<p class="panel-label">View Options</p>', markup)
        self.assertNotIn('id="detailLinks"', markup)
        self.assertNotIn('Direct links', markup)
        self.assertIn(".radar-widget", styles)
        self.assertIn(".radar-stats", styles)
        self.assertIn(".source-control-stack", styles)
        self.assertIn(".stat-toggle", styles)
        self.assertIn(".timeline-strip", styles)
        self.assertIn(".category-legend button.is-dimmed", styles)
        self.assertIn("hiddenClusters: new Set()", script)
        self.assertIn("hiddenHubConnections: new Set()", script)
        self.assertIn("function updateHubClusterLegend", script)
        self.assertIn("function isHiddenByHubConnection", script)
        self.assertIn("function buildTourSlugs", script)
        self.assertIn("function visibleTopHubs", script)
        self.assertIn("function passesTimeline", script)
        self.assertIn("function drawClusterClouds", script)
        self.assertIn("function degreeIntensity", script)
        self.assertIn("selectionHistory: { slugs: [], index: -1, navigating: false }", script)
        self.assertIn("function navigateSelectionHistory", script)
        self.assertIn("recordSelectionHistory(entity.slug)", script)
        self.assertIn("const categorySlots = new Map()", script)
        self.assertIn("hubGlow", script)
        self.assertIn("edgeLayer", script)
        self.assertIn('`Click to show ${category} cluster`', script)
        self.assertIn('`Click to hide ${category} cluster`', script)
        self.assertIn('`Click to show direct connections of ${node.label || node.slug}`', script)
        self.assertIn('`Click to hide direct connections of ${node.label || node.slug}`', script)

    def test_filter_yoda_selection_and_autopilot_polish(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="mapFilterToggleButton"', markup)
        self.assertLess(markup.index('id="mapFilterToggleButton"'), markup.index('id="mapFilterPanel"'))
        self.assertIn(".graph-canvas-wrap > .new-node-floating", styles)
        self.assertIn(".graph-canvas-wrap > .map-filter-panel", styles)
        self.assertIn("left: 18px", styles)
        self.assertIn("right: auto", styles)
        self.assertIn("top: 50%", styles)
        self.assertIn("max-height: min(76%, 560px)", styles)
        self.assertIn("align-content: start", styles)
        self.assertIn("grid-auto-rows: max-content", styles)
        self.assertIn("<p class=\"panel-label\">Clusters</p>", markup)
        self.assertIn("<p class=\"panel-label\">Hot Hubs</p>", markup)
        self.assertIn("<span>Top</span>", markup)
        self.assertNotIn("<span>Top hubs</span>", markup)
        self.assertIn('yoda-avatar-image" src="/assets/brand/yoda-selection-avatar.png?v=1.0.119"', markup)
        self.assertIn('src="/assets/brand/yoda-selection-avatar.png?v=1.0.119"', markup)
        self.assertIn("object-fit: contain", styles)
        self.assertIn("overflow: hidden", styles)
        self.assertIn(".selection-actions", styles)
        self.assertIn("gap: 1px", styles)
        self.assertIn('id="selectionViewButton"', markup)
        self.assertIn("selectionViewButton?.addEventListener", script)
        self.assertIn("padding: 1px", styles)
        self.assertIn(".autopilot-flyout.tour-docked", styles)
        self.assertIn("left: 50%", styles)
        self.assertIn("transform: translateX(-50%)", styles)
        self.assertIn("opacity: 0.34", styles)
        self.assertIn(".autopilot-flyout.tour-docked:hover", styles)
        self.assertIn("tourCounter.hidden = false", script)
        self.assertIn("panel === autopilotFlyout && (state.tour.active || state.tour.toolbarPinned)", script)
        self.assertNotIn("state.tour.toolbarPinned || (autopilotFlyout && !autopilotFlyout.hidden)", script)
        self.assertIn("showFloatingPanel(autopilotFlyout, navAutopilotButton);", script)
        self.assertIn("updateResponsiveSelectionPlacement", script)
        self.assertIn("orderedSearchSlugs", script)
        self.assertIn("backendRankBoost", script)

    def test_top_search_and_filter_band_is_compact_and_category_based(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertNotIn("Search entities", markup)
        self.assertNotIn("Constellation View", markup)
        self.assertIn('rel="icon" type="image/png" href="/assets/brand/logo-circle-transparent.png"', markup)
        self.assertIn('rel="apple-touch-icon" href="/assets/brand/logo-circle-transparent.png"', markup)
        self.assertIn('class="nav-logo"', markup)
        self.assertIn('class="graph-wordmark"', markup)
        self.assertIn('class="graph-wordmark-link has-tooltip"', markup)
        self.assertIn('src="/assets/brand/wordmark-line-small.png"', markup)
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "logo-circle-transparent.png").exists())
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "wordmark-line.png").exists())
        self.assertTrue((ROOT / "public" / "assets" / "brand" / "wordmark-line-small.png").exists())
        self.assertIn('href="https://github.com/techtony2018/memory-stargraph"', markup)
        self.assertIn("Matches", markup)
        self.assertIn(">Links</span>", markup)
        self.assertNotIn('id="categoryFilter"', markup)
        self.assertNotIn('id="clearFiltersButton"', markup)
        self.assertNotIn('id="tagFilter"', markup)
        self.assertNotIn('id="typeFilter"', markup)
        self.assertIn("has-tooltip", markup)
        self.assertIn(".has-tooltip::before", styles)
        self.assertIn("top: calc(100% + 8px)", styles)
        self.assertNotIn('class="search-wrap has-tooltip"', markup)
        self.assertNotIn("select-filter", styles)
        self.assertNotIn("list-filter", styles)
        self.assertNotIn("top-metrics", styles)
        self.assertIn("zoom-floating", styles)
        self.assertIn("zoom-icon-button", styles)
        self.assertIn("cluster-icon-button", styles)
        self.assertIn("left: 18px", styles)
        self.assertIn("top: 18px", styles)
        self.assertIn("flex-direction: row", styles)
        self.assertIn("opacity: 0.24", styles)
        self.assertIn("min-width: 252px", styles)
        self.assertIn(".plan-controls", styles)
        self.assertIn(".plan-action-row", styles)
        self.assertIn(".plan-number-field", styles)
        self.assertIn('fillButton.textContent = "Fill"', script)
        self.assertIn('addCurrent.textContent = "Add"', script)
        self.assertIn('clearButton.textContent = "Clear"', script)
        self.assertIn('"This will fully erase current autopilot plan, are you sure?"', script)
        self.assertIn('confirm.textContent = isClearConfirm ? "Clear" : "Generate"', script)
        self.assertIn("draft.splice(0, draft.length);", script)
        self.assertIn('empty.textContent = "No planned nodes. Fill or Add."', script)
        self.assertIn('"Auto generated list"', script)
        self.assertIn('"Manual plan"', script)
        self.assertNotIn('selectedTitle', script)
        self.assertIn(".plan-row", styles)
        self.assertIn("#tourButton {\n  width: 34px", styles)
        self.assertIn("zoom-level", styles)
        self.assertIn("z-index: 20", styles)
        self.assertIn("z-index: 50", styles)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(270px, 0.36fr)", styles)
        self.assertIn("resize: vertical", styles)
        self.assertIn("max-height: calc(1.65em * 5)", styles)
        self.assertNotIn("focused", markup)
        self.assertNotIn("neighborhood", markup)
        self.assertNotIn("search match", markup)
        self.assertIn("flex: 1 1 300px", styles)
        self.assertIn("min-width: 220px", styles)
        self.assertIn('href="/styles.css?v=1.0.119"', markup)
        self.assertIn('src="/app.js?v=1.0.119"', markup)
        self.assertIn('const UI_VERSION = "V1.0.119"', script)
        self.assertIn("height: 28px", styles)
        self.assertIn("align-items: center", styles)
        self.assertIn("filters: { minDegree: 0 }", script)
        self.assertNotIn("function renderCategoryFilter", script)
        self.assertNotIn("function renderMultiSelectFilter", script)
        self.assertNotIn("function updateMultiSelectFilter", script)
        self.assertNotIn("All Category", script)
        self.assertNotIn('"All Tags"', script)
        self.assertNotIn('value: "__untagged__"', script)
        self.assertNotIn("state.filters.tags", script)
        self.assertNotIn("state.filters.type", script)
        self.assertIn("zoomLevel", script)
        self.assertIn("updateCloudModeControl", script)
        self.assertNotIn("cloudModeButton.textContent", script)
        self.assertIn("displaySummary", script)
        self.assertIn('["summary", "metadata"].includes', script)

    def test_backlinks_modal_loads_immediately(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('modalMessage.textContent = "Loading backlinks..."', script)
        self.assertIn('renderBacklinksView(response.data.output || "(No backlinks)", slug)', script)
        self.assertIn("function renderBacklinksView", script)
        self.assertIn("backlink-from-link", script)
        self.assertIn("allTargetsAreSelected", script)
        self.assertIn('setHudTooltip(link, `Open ${item.from_slug}`)', script)
        self.assertIn('apiPost(`/api/entity-backlinks/${encodeURIComponent(slug)}`, {})', script)
        self.assertIn("data-backlink-slug", script)
        self.assertIn('linkBack.textContent = "+"', script)
        self.assertIn('setHudTooltip(linkBack, "Add relationship")', script)
        self.assertNotIn('source: ${item.link_source}', script)
        self.assertNotIn('row.appendChild(meta)', script)
        self.assertIn("openReverseRelationshipModal", script)
        self.assertIn('state.modalAction = { action: "result", slug, label }', script)
        self.assertNotIn('modalPrimaryButton.textContent = "Load backlinks"', script)
        self.assertNotIn('modalEditor.value = response.data.output || "(No backlinks)"', script)

    def test_relationship_view_and_backlinks_use_compact_wiki_rows(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('data-action="view-relationships">Relationships</button>', markup)
        self.assertIn('data-action="backlinks">Backlinks</button>', markup)
        self.assertIn('data-action="graph-query">Query</button>', markup)
        self.assertIn('data-action="history">History</button>', markup)
        self.assertLess(markup.index('data-action="attach-file"'), markup.index('data-action="graph-query"'))
        self.assertLess(markup.index('data-action="attach-file"'), markup.index('data-action="timeline-view"'))
        self.assertLess(markup.index('data-action="attach-file"'), markup.index('data-action="history"'))
        self.assertNotIn('data-action="add-link">Add relationship</button>', markup)
        self.assertNotIn('data-action="remove-link">Remove relationship</button>', markup)
        self.assertNotIn('Graph query from here</button>', markup)
        self.assertNotIn('View history</button>', markup)
        self.assertNotIn('Show backlinks</button>', markup)
        self.assertIn("function renderRelationshipWikiList", script)
        self.assertIn("function renderRelationshipsMessage", script)
        self.assertIn("function openSelectedRelationshipModal", script)
        self.assertIn("function renderOutgoingRelationshipsView", script)
        self.assertIn("function parseOutgoingRelationshipItems", script)
        self.assertIn('apiPost(`/api/entity-graph-query/${encodeURIComponent(slug)}`', script)
        self.assertIn('direction: "outgoing"', script)
        self.assertIn("function currentRelationshipPage", script)
        self.assertIn("function clampRelationshipPage", script)
        self.assertIn("RELATIONSHIP_PAGE_SIZE = 10", script)
        self.assertIn("function outgoingRelationshipOptions", script)
        self.assertIn("edge.source.slug === slug", script)
        self.assertIn("edge.target.slug !== slug", script)
        self.assertIn(".slice(start, start + RELATIONSHIP_PAGE_SIZE)", script)
        self.assertIn("relationship-pagination", script)
        self.assertIn("relationshipPrevPage", script)
        self.assertIn("relationshipNextPage", script)
        self.assertIn("function relationshipPageWindow", script)
        self.assertIn("relationship-page-number", script)
        self.assertIn("relationship-page-total", script)
        self.assertIn('button.setAttribute("aria-current", pageIndex === page ? "page" : "false")', script)
        self.assertIn("Math.min(totalPages, startPage + 10)", script)
        self.assertIn("relationship-wiki-list", script)
        self.assertIn("relationship-source-link", script)
        self.assertIn("relationship-add-backlink", script)
        self.assertIn("relationship-remove", script)
        self.assertIn('removeButton.setAttribute("aria-label", "Remove relationship")', script)
        self.assertIn('addButton.setAttribute("aria-label", "Add backlink")', script)
        self.assertIn('addButton.setAttribute("aria-label", "Add relationship")', script)
        self.assertIn('if (action === "view-relationships")', script)
        self.assertIn('modalKicker.textContent = "Relationships"', script)
        self.assertIn('modalKicker.textContent = "Query"', script)
        self.assertIn('modalKicker.textContent = "History"', script)
        self.assertNotIn('modalKicker.textContent = "View relationship"', script)
        self.assertNotIn('modalKicker.textContent = "View Relationships"', script)
        self.assertNotIn('modalKicker.textContent = "Graph query from here"', script)
        self.assertNotIn('modalKicker.textContent = "View history"', script)
        self.assertIn(".relationship-wiki-list", styles)
        self.assertIn(".relationship-icon-button", styles)
        self.assertIn(".relationship-page-number[aria-current=\"page\"]", styles)
        self.assertIn("grid-template-columns: minmax(0, 1fr) auto auto auto", styles)

    def test_memory_tour_waits_for_selection_load_before_advancing(self):
        script = (ROOT / "public/app.js").read_text()
        tour_start = script.index("async function showTourStop")
        tour_end = script.index("function setSearchLoading", tour_start)
        tour_block = script[tour_start:tour_end]

        self.assertIn("timer: null", script)
        self.assertIn("pending: false", script)
        self.assertIn("timeoutTimer: null", script)
        self.assertIn("let tourNodeLoadTimeoutMs = 20 * 1000", script)
        self.assertIn("partialTimeoutSlugs: new Set()", script)
        self.assertIn('id="tourCounter"', (ROOT / "public" / "index.html").read_text())
        self.assertIn("function scheduleNextTourStop", script)
        self.assertIn("function selectionIsLoadedForTour", script)
        self.assertIn("function clearTourPending", script)
        self.assertIn("function handleTourNodeTimeout", script)
        self.assertIn("function updateTourCounter", script)
        self.assertIn("await waitForTourSelectionLoad(slug)", script)
        self.assertIn("resolve(handleTourNodeTimeout(slug))", script)
        self.assertIn("tourNodeLoadTimeoutMs + 5000", script)
        self.assertIn("state.tour.partialTimeoutSlugs.add(slug)", script)
        self.assertIn("state.tour.invalidPlanSlugs.has(slug)", script)
        self.assertIn("state.tour.invalidPlanSlugs.add(slug)", script)
        self.assertIn('result?.status === "partial"', script)
        self.assertIn('result?.status === "error"', script)
        self.assertIn("function handleTourNodeError", script)
        self.assertIn('console.warn("Autopilot node load failed"', script)
        self.assertIn('return { status: "partial", slug, httpStatus: response.status }', script)
        self.assertIn("Basic graph info is available, but no markdown page was found", script)
        self.assertIn("Partial info loaded for", script)
        self.assertNotIn("Autopilot timeout: skipped", script)
        self.assertIn("window.setTimeout(() => clearTourPending(slug), tourNodeLoadTimeoutMs + 5000)", script)
        self.assertNotIn("window.setInterval(() =>", tour_block)

    def test_selection_media_preview_uses_first_media_or_selected_slug(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="selectionMediaPreview"', markup)
        self.assertIn('id="selectionMediaSlug"', markup)
        self.assertIn("function renderSelectionMediaPreview", script)
        self.assertIn("apiGet(`/api/entity-media/${encodeURIComponent(slug)}`)", script)
        self.assertIn('selectionMediaPreview.textContent = "loading media.."', script)
        self.assertIn('selectionMediaPreview.classList.add("is-loading")', script)
        self.assertIn('selectionMediaPreview.classList.remove("is-loading")', script)
        self.assertIn('selectionMediaSlug.textContent = slug || "No selection"', script)
        self.assertIn(".selection-blueprint.has-media", styles)
        self.assertIn(".selection-media-preview.is-loading", styles)
        self.assertIn("text-overflow: ellipsis", styles)
        self.assertNotIn("NODE · ID: 001", markup + script)

    def test_settings_exposes_configurable_local_cache(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="navSettingsButton"', markup)
        self.assertIn('class="settings-section"', markup)
        self.assertLess(markup.index("<h3>Display</h3>"), markup.index("<h3>Cache</h3>"))
        self.assertIn("<h3>Cache</h3>", markup)
        self.assertNotIn("<h3>Refresh</h3>", markup)
        self.assertIn("<h3>Yoda</h3>", markup)
        self.assertIn('id="yodaDepthInput"', markup)
        self.assertIn('id="settingsYodaLogButton"', markup)
        self.assertIn('settingsYodaLogButton?.addEventListener("click"', script)
        self.assertIn('data-tooltip="Graph hops for Ask Yoda context."', markup)
        self.assertIn("function setYodaDepth", script)
        self.assertIn("function syncYodaDepthControl", script)
        self.assertIn('value="4"', markup)
        self.assertIn('id="cacheLimitInput"', markup)
        self.assertIn('id="flushCacheButton"', markup)
        self.assertIn('value="10"', markup)
        self.assertIn('id="settingsOkButton"', markup)
        self.assertIn('id="settingsCancelButton"', markup)
        self.assertIn('id="cacheUsageValue"', markup)
        self.assertIn('class="cache-usage-label"', markup)
        self.assertNotIn('id="cacheUsageValue" class="source-badge', markup)
        self.assertIn("Used 0 B", markup)
        self.assertNotIn('id="lastRefresh"', markup)
        self.assertNotIn('id="autoRefreshToggle"', markup)
        self.assertNotIn('id="autoRefreshInterval"', markup)
        self.assertNotIn('class="refresh-inline-controls"', markup)
        self.assertNotIn("autoRefresh: { enabled:", script)
        self.assertNotIn("function scheduleAutoRefresh", script)
        self.assertIn("NODE_CACHE_DEFAULT_BYTES", script)
        self.assertIn("const NODE_CACHE_DEFAULT_BYTES = 10 * 1024 * 1024", script)
        self.assertIn("NODE_CACHE_MAX_BYTES", script)
        self.assertIn("function flushNodeCache", script)
        self.assertIn("flushCacheButton?.addEventListener", script)
        self.assertIn("pendingSettings: null", script)
        self.assertIn("function snapshotSettings", script)
        self.assertIn("function applySettingsFromControls", script)
        self.assertIn("function cancelSettingsChanges", script)
        self.assertIn("YODA_CONTEXT_DEPTH_KEY", script)
        self.assertIn("yodaDepth: readNumberSetting(YODA_CONTEXT_DEPTH_KEY, 4, 1, 6)", script)
        self.assertIn("function cacheGet", script)
        self.assertIn("function cacheSet", script)
        self.assertIn("function enforceCacheLimit", script)
        self.assertIn("updateCacheSettingsView", script)
        self.assertNotIn("0 disables cache", markup)
        self.assertIn(".settings-flyout", styles)
        self.assertIn("left: 22px", styles)
        self.assertIn("right: auto", styles)
        self.assertIn('panel === settingsFlyout', script)
        self.assertIn('panel.style.left = "22px"', script)
        self.assertIn('panel.style.right = "auto"', script)

    def test_ask_yoda_uses_agent_chat_action(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertLess(markup.index('data-action="view"'), markup.index('data-action="ask-yoda"'))
        self.assertLess(markup.index('data-action="ask-yoda"'), markup.index('data-action="timeline-view"'))
        self.assertNotIn('data-action="ask">Ask GBrain</button>', markup)
        self.assertIn('id="selectionAskYodaButton"', markup)
        self.assertIn('id="mapViewButton"', markup)
        self.assertIn('id="mapAskYodaButton"', markup)
        self.assertIn('class="yoda-avatar yoda-avatar-image"', markup)
        self.assertLess(markup.index('id="selectionAskYodaButton"'), markup.index('id="historyBackButton"'))
        self.assertIn("selectionAskYodaButton?.addEventListener", script)
        self.assertIn("mapViewButton?.addEventListener", script)
        self.assertIn("mapAskYodaButton?.addEventListener", script)
        self.assertIn("function updateAskYodaButtons", script)
        self.assertIn('detailTitle?.addEventListener("dblclick"', script)
        self.assertIn('if (state.focusSlug) void openNodeModal("view", state.focusSlug)', script)
        self.assertIn("askYodaChats: new Map()", script)
        self.assertIn('id="modalYodaDepth"', markup)
        self.assertIn('id="modalYodaDepthWrap"', markup)
        self.assertIn('history.push({ role: "assistant", content: "Thinking", pending: true', script)
        self.assertNotIn('apiPost(`/api/entity-ask/${encodeURIComponent(slug)}`', script)
        self.assertIn('modalKicker.textContent = "Ask Yoda"', script)
        self.assertIn('apiPost(`/api/entity-ask-yoda/${encodeURIComponent(slug)}`, { question, history: historyPayload, depth: state.yodaDepth })', script)
        self.assertIn("renderAskChat(slug, label, { mode: \"yoda\" })", script)
        self.assertIn("chat-slug-link", styles := (ROOT / "public" / "styles.css").read_text())
        self.assertIn("thinking-dots", styles)

    def test_filter_sidebar_auto_hides_from_right_drawer_and_stays_open_inside_panel(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="filterDrawerHandle"', markup)
        self.assertIn('class="filter-sidebar-drawer has-tooltip"', markup)
        self.assertIn('data-tooltip="Show graph filters."', markup)
        self.assertIn('id="mapFilterPanel" class="map-filter-panel is-hidden"', markup)
        self.assertIn("mapFiltersVisible: false", script)
        self.assertIn("function showFilterSidebar", script)
        self.assertIn("function hideFilterSidebar", script)
        self.assertIn("middle third", script)
        self.assertIn("right side middle third", script)
        self.assertIn("filterDrawerHandle?.addEventListener(\"pointerenter\"", script)
        self.assertIn("function pointerStayedInsideFilterSidebar", script)
        self.assertIn("pointerStayedInsideFilterSidebar(event.relatedTarget)", script)
        self.assertIn("mapFilterPanel?.addEventListener(\"click\", showFilterSidebar)", script)
        self.assertIn(".filter-sidebar-drawer", styles)
        self.assertIn("right: 0", styles)
        self.assertIn("width: 34px", styles)
        self.assertIn(".filter-sidebar-drawer::before", styles)
        self.assertIn("width: 12px", styles)
        self.assertIn("border-radius: 8px 0 0 8px", styles)
        self.assertIn("right: 18px", styles)
        self.assertIn("width: min(238px, calc(100% - 34px))", styles)

    def test_relationship_mutations_evict_endpoint_cache_and_refresh_visible_views(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function invalidateNodeCacheForSlug", script)
        self.assertIn("function invalidateRelationshipEndpointCache", script)
        self.assertIn("invalidateRelationshipEndpointCache(slug, target)", script)
        self.assertIn("await refreshSelectedNodeAfterRelationshipMutation(slug, target, \"add-link\")", script)
        self.assertIn("await refreshSelectedNodeAfterRelationshipMutation(slug, target, \"remove-link\")", script)
        self.assertIn("state.relationshipPages", script)
        self.assertIn("state.backlinkPages", script)

    def test_graph_render_uses_dirty_idle_loop_and_culls_hidden_nodes(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("renderDirty: true", script)
        self.assertIn("function requestRender", script)
        self.assertIn("function shouldAnimateContinuously", script)
        self.assertIn("function ensureRenderLoop", script)
        self.assertIn("if (!shouldAnimateContinuously())", script)
        self.assertIn("state.animationHandle = null", script)
        self.assertIn("function nodeIsDrawable", script)
        self.assertIn("const drawableNodes = () => state.nodes.filter(nodeIsDrawable)", script)
        self.assertIn("const drawableEdges = () => state.edges.filter((edge) => nodeIsDrawable(edge.source) && nodeIsDrawable(edge.target))", script)
        self.assertIn("flowingEdgeIsAnimated", script)
        self.assertIn("isImportantNodeForLod", script)

    def test_autopilot_launch_icon_and_radar_polish_are_present(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="tourButton"', markup)
        self.assertIn('aria-label="Play Autopilot"', markup)
        self.assertIn('id="tourPlanButton"', markup)
        self.assertIn('id="tourStopButton"', markup)
        self.assertIn('id="autopilotModeIcon" class="autopilot-mode-icon has-tooltip"', markup)
        self.assertIn('class="autopilot-icon play-icon"', markup)
        self.assertIn('id="tourCounter"', markup)
        self.assertIn('id="metrics"', markup)
        self.assertIn("width: 138px", styles)
        self.assertIn("height: 138px", styles)
        self.assertIn("#tourButton {\n  width: 34px", styles)
        self.assertNotIn(">N</", markup)

    def test_source_path_fields_render_as_safe_file_links(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function localFileHrefForValue", script)
        self.assertIn("function appendLocalSourcePathLinks", script)
        self.assertIn('fieldName === "source_path"', script)
        self.assertIn('Local source path:', script)
        self.assertIn('link.setAttribute("href", fileHref)', script)
        self.assertIn('link.textContent = value', script)
        self.assertIn('link.target = "_blank"', script)
        self.assertIn('return `file://${encodedPath}`', script)
        self.assertIn('return ""', script)

    def test_view_markdown_linkifies_web_addresses(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function cleanWebAddressParts", script)
        self.assertIn("function webAddressHrefForValue", script)
        self.assertIn("function appendWebAddressLink", script)
        self.assertIn("function appendWebAddressLinks", script)
        self.assertIn("appendWebAddressLinks(parent, part)", script)
        self.assertIn("appendLocalFileLinks(parent, value.slice(cursor, addressOffset))", script)
        self.assertIn("appendLocalFileLinks(parent, value.slice(cursor))", script)
        self.assertIn("/^https?:\\/\\//i.test(address)", script)
        self.assertIn('return `https://${address}`', script)
        self.assertIn("link.href = href", script)
        self.assertIn('link.target = "_blank"', script)
        self.assertIn('link.rel = "noopener noreferrer"', script)
        self.assertIn("link.textContent = address", script)
        self.assertIn("if (suffix) parent.appendChild(document.createTextNode(suffix))", script)
        self.assertIn("[^\\s<>\"`]+", script)
        self.assertIn("(?:[a-z0-9-]+\\.)+[a-z]{2,}", script)
        self.assertIn("cleanMarkdownDestination(url)", script)
        self.assertIn("link.textContent = label || url", script)

    def test_history_auto_loads_and_shows_selected_slug(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('data-action="history">History</button>', markup)
        self.assertNotIn('modalPrimaryButton.textContent = "Load history"', script)
        self.assertIn("async function loadHistoryForSlug", script)
        self.assertIn('renderMarkdownView(`Slug: ${slug}\\n\\nLoading history...`)', script)
        self.assertIn('renderMarkdownView(`Slug: ${slug}\\n\\n${response.data.output || "(No history)"}`)', script)
        self.assertIn('modalKicker.textContent = "History"', script)

    def test_relationship_add_uses_cached_and_live_target_search(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function cachedEntitySearchResults", script)
        self.assertIn("function createSlugSelector", script)
        self.assertIn("function renderSlugSelectorOptions", script)
        self.assertIn("function runLiveSlugSelectorSearch", script)
        self.assertIn("function mergeRelationshipTargetOptions", script)
        self.assertIn("async function runLiveRelationshipTargetSearch", script)
        self.assertIn('beginBusyOperation(`Searching targets for ${query}`)', script)
        self.assertIn('apiGet(`/api/search?q=${encodeURIComponent(query)}`)', script)
        self.assertIn('createSlugSelector({', script)
        self.assertIn('id: "operationTarget"', script)
        self.assertIn('input.addEventListener("input"', script)
        self.assertIn('input.addEventListener("keydown"', script)
        self.assertIn('event.key === "Enter"', script)
        self.assertIn("state.slugSelectorSearch", script)
        self.assertIn("modalPrimaryButton.disabled = true", script)

    def test_slug_selector_uses_compact_hud_popup_not_native_datalist(self):
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public/styles.css").read_text()

        self.assertIn("function positionSlugSelectorPopup", script)
        self.assertIn("function showSlugSelectorPopup", script)
        self.assertIn("function hideSlugSelectorPopup", script)
        self.assertIn("document.body.appendChild(popup)", script)
        self.assertIn('popup.className = "slug-selector-popup"', script)
        self.assertIn('popup.setAttribute("role", "listbox")', script)
        self.assertIn('input.setAttribute("aria-controls", popup.id)', script)
        self.assertIn('input.removeAttribute("list")', script)
        self.assertNotIn('input.setAttribute("list", `${id}Options`)', script)
        self.assertNotIn('list.id = `${id}Options`', script)
        self.assertNotIn("slug-selector-panel", script)
        self.assertNotIn("row.appendChild(document.getElementById(`planSlug${index}Options`))", script)
        self.assertIn(".slug-selector-popup", styles)
        self.assertIn("position: fixed", styles)
        self.assertIn("backdrop-filter: blur(14px)", styles)
        self.assertIn(".slug-selector-option", styles)
        self.assertIn(".slug-selector-option:hover", styles)

    def test_relationship_type_selector_uses_hud_popup_and_live_discovery(self):
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public/styles.css").read_text()

        self.assertIn("function createRelationshipTypeSelector", script)
        self.assertIn("function cachedRelationshipTypeResults", script)
        self.assertIn("function runLiveRelationshipTypeSearch", script)
        self.assertIn("function parseRelationshipTypesFromOutput", script)
        self.assertIn('id: "operationLinkType"', script)
        self.assertIn('popup.className = "slug-selector-popup relationship-type-selector-popup"', script)
        self.assertIn('beginBusyOperation(`Discovering relationship types for ${query}`)', script)
        self.assertIn('apiPost(`/api/entity-graph-query/${encodeURIComponent(sourceSlug)}`', script)
        self.assertIn('input.removeAttribute("list")', script)
        self.assertNotIn("operationLinkTypeOptions", script)
        self.assertIn(".slug-selector-popup", styles)
        self.assertIn(".slug-selector-option", styles)

    def test_tooltips_are_hud_only_without_native_titles(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function setHudTooltip", script)
        self.assertIn("element.removeAttribute(\"title\")", script)
        self.assertNotIn(' title="', markup)
        self.assertNotRegex(script.replace("document.title =", "documentTitle ="), r"\.title\s*=")
        self.assertIn('class="graph-wordmark-link has-tooltip"', markup)
        self.assertIn('id="uiVersion" class="ui-version ui-version-link has-tooltip"', markup)

    def test_static_actionable_controls_have_text_or_hud_tooltip(self):
        markup = (ROOT / "public" / "index.html").read_text()
        parser = ActionableControlParser()
        parser.feed(markup)

        missing = []
        for control in parser.controls:
            attrs = control["attrs"]
            text = "".join(control["text"]).strip()
            has_hud_tooltip = "has-tooltip" in attrs.get("class", "") and attrs.get("data-tooltip")
            has_clear_visible_text = bool(text) and text not in {"×", "‹", "›", "+", "-", "?"}
            if not has_hud_tooltip and not has_clear_visible_text:
                missing.append(attrs.get("id") or attrs.get("data-action") or control["tag"])

        self.assertEqual(missing, [])

    def test_dynamic_controls_restore_hud_tooltip_coverage(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function setModalControlTooltips", script)
        self.assertIn('setHudTooltip(modalCloseButton, "Close this window.")', script)
        self.assertIn("setHudTooltip(modalPrimaryButton", script)
        self.assertIn("setHudTooltip(modalCancelButton", script)
        self.assertIn('setHudTooltip(hiddenListButton, "Restore this hidden category.")', script)
        self.assertIn('setHudTooltip(editButton, "Edit this node markdown.")', script)
        self.assertIn('setHudTooltip(previous, "Previous page.")', script)
        self.assertIn('setHudTooltip(next, "Next page.")', script)
        self.assertIn('setHudTooltip(row, `Select ${node.slug}`)', script)
        self.assertIn('setHudTooltip(row, `Use relationship type ${option}`)', script)
        self.assertIn('setHudTooltip(addCurrent, "Add the currently selected node to the manual plan.")', script)
        self.assertIn('setHudTooltip(clearButton, "Clear every manual plan row.")', script)
        self.assertIn('setHudTooltip(cancel, "Keep the current manual plan.")', script)
        self.assertIn('setHudTooltip(confirm, "Replace the manual plan with generated rows.")', script)

    def test_ask_yoda_hidden_fallback_reveal_ui(self):
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public/styles.css").read_text()

        self.assertIn("fallbackOutput", script)
        self.assertIn("renderHiddenFallbackReveal", script)
        self.assertIn("click to see result from Ask GBrain", script)
        self.assertIn("Ask GBrain fallback output", script)
        self.assertIn("response.data.fallback_output", script)
        self.assertIn("message.fallbackOutput", script)
        self.assertIn(".chat-fallback-reveal", styles)
        self.assertIn(".chat-fallback-output", styles)

    def test_settings_flyout_pins_after_interaction(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("settingsPinned: false", script)
        self.assertIn("function pinSettingsFlyout()", script)
        self.assertIn("settingsFlyout?.addEventListener(\"pointerdown\", pinSettingsFlyout)", script)
        self.assertIn("settingsFlyout?.addEventListener(\"focusin\", pinSettingsFlyout)", script)
        self.assertIn("settingsFlyout?.addEventListener(\"input\", pinSettingsFlyout)", script)
        self.assertIn("settingsFlyout?.addEventListener(\"change\", pinSettingsFlyout)", script)
        self.assertIn("if (!state.settingsPinned)", script)
        self.assertIn("state.settingsPinned = false;", script)

    def test_ask_yoda_view_log_diagnostics_are_exposed(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="modalYodaLogButton"', markup)
        self.assertNotIn('id="modalYodaLogButton" class="ghost-button compact-button" type="button" hidden', markup)
        self.assertIn("function yodaLogSlug", script)
        self.assertIn("function formatYodaDiagnosticLog", script)
        self.assertIn("function openYodaLogWindow", script)
        self.assertIn("function rememberYodaLog", script)
        self.assertIn("function returnFromYodaLog", script)
        self.assertIn("operationModal.hidden = false", script)
        self.assertIn("state.askYodaLogs", script)
        self.assertIn("function globalYodaLogEntries", script)
        self.assertIn("entries.slice(0, limit)", script)
        self.assertIn("globalYodaLogEntries(20)", script)
        self.assertIn("nodeYodaLogEntries(slug, 8)", script)
        self.assertIn("openYodaLogWindow({ scope: \"global\" })", script)
        self.assertIn("openYodaLogWindow({ scope: \"node\", slug: yodaLogSlug() })", script)
        self.assertIn("request_id", script)
        self.assertIn("model_status", script)
        self.assertIn("fallback_used", script)
        self.assertIn("timing phases", script)
        self.assertNotIn("modalYodaLogButton.hidden =", script)
        self.assertIn(".yoda-log-window", styles)

    def test_zoom_label_resets_zoom_to_100_percent(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="zoomLevel" class="zoom-level has-tooltip"', markup)
        self.assertIn('role="button"', markup)
        self.assertIn('aria-label="Reset zoom to 100%"', markup)
        self.assertIn("function resetZoom()", script)
        self.assertIn("setZoom(1)", script)
        self.assertIn('zoomLevel?.addEventListener("click", resetZoom)', script)
        self.assertIn('zoomLevel?.addEventListener("keydown"', script)
        self.assertIn("event.key === \"Enter\" || event.key === \" \"", script)
        self.assertIn(".zoom-level", styles)
        self.assertIn("cursor: pointer", styles)

    def test_plan_cache_misses_are_not_invalid_until_playback_fetch_fails(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("invalidPlanSlugs: new Set()", script)
        self.assertIn("state.tour.invalidPlanSlugs.has(slug)", script)
        self.assertIn("state.tour.invalidPlanSlugs.add(slug)", script)
        self.assertIn("state.tour.invalidPlanSlugs.delete(draft[index])", script)
        self.assertIn("state.tour.invalidPlanSlugs.delete(nextSlug)", script)
        self.assertNotIn("!state.tour.partialTimeoutSlugs.has(slug) && !isValidPlanSlug(slug)", script)

    def test_autopilot_pauses_on_manual_search_or_map_selection(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("function pauseTourForManualSelection(reason)", script)
        self.assertIn('pauseTourForManualSelection("manual search")', script)
        self.assertIn('pauseTourForManualSelection("manual map selection")', script)
        self.assertIn('loadEntity(node.slug, { source: "manual-map" })', script)
        self.assertIn("Autopilot paused: ${reason}", script)

    def test_common_slug_selector_uses_hud_styled_list(self):
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn("function createSlugSelector", script)
        self.assertIn('const popup = document.createElement("div")', script)
        self.assertIn('popup.className = "slug-selector-popup"', script)
        self.assertIn("showSlugSelectorPopup(selector, options)", script)
        self.assertIn("slug-selector-option", script)
        self.assertIn(".slug-selector-popup", styles)
        self.assertIn(".slug-selector-option", styles)
        self.assertIn(".slug-selector-empty", styles)

    def test_media_nodes_render_white_center_dot(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn("mediaSlugs: new Set()", script)
        self.assertIn("function nodeHasMediaMarker", script)
        self.assertIn("function rememberNodeMediaStatus", script)
        self.assertIn("node.has_media", script)
        self.assertIn("ctx.fillStyle = \"rgba(255, 255, 255, 0.92)\"", script)
        self.assertIn("nodeHasMediaMarker(node)", script)

    def test_busy_indicator_covers_long_running_ui_operations(self):
        markup = (ROOT / "public" / "index.html").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('id="busyIndicator"', markup)
        self.assertIn('class="busy-indicator"', markup)
        self.assertIn("function beginBusyOperation", script)
        self.assertIn("function endBusyOperation", script)
        self.assertIn("setBusyIndicator(", script)
        self.assertIn('beginBusyOperation("Searching")', script)
        self.assertIn('beginBusyOperation("Loading view")', script)
        self.assertIn('`Loading direct neighbors for ${requestedNode.label || slug}`', script)
        self.assertIn("function setBusyOperationLabel", script)
        self.assertIn("setBusyOperationLabel(directBusyToken", script)
        self.assertIn("endBusyOperation(directBusyToken)", script)
        self.assertIn('beginBusyOperation("Loading backlinks")', script)
        self.assertIn('"add-link": "Saving relationship"', script)
        self.assertIn('delete: "Deleting node"', script)
        self.assertIn('timeline: "Updating timeline"', script)
        self.assertIn('"attach-file": "Attaching file"', script)
        self.assertIn('embed: "Refreshing embedding"', script)
        self.assertIn(".busy-indicator", styles)
        self.assertIn("@keyframes busy-spin", styles)
        self.assertIn("left: 50%", styles)
        self.assertIn("top: 50%", styles)
        self.assertIn("transform: translate(-50%, -50%)", styles)

    def test_map_filters_autopilot_and_mobile_overlays_are_inside_canvas(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('id="mapFilterToggleButton"', markup)
        self.assertIn('id="mapFilterPanel"', markup)
        self.assertLess(markup.index('id="newNodeButton"'), markup.index('id="mapFilterToggleButton"'))
        self.assertLess(markup.index('id="mapFilterPanel"'), markup.index('class="canvas-overlay"'))
        self.assertIn('class="autopilot-icon play-icon"', markup)
        self.assertIn("mapFilterPanel?.classList.toggle", script)
        self.assertIn("state.mapFiltersVisible", script)
        self.assertIn(".map-filter-panel", styles)
        self.assertIn(".map-filter-toggle-button", styles)
        self.assertIn(".autopilot-flyout.tour-docked", styles)
        self.assertIn(".graph-canvas-wrap > .canvas-overlay", styles)
        self.assertIn("@media (max-width: 720px)", styles)
        self.assertIn(".graph-canvas-wrap > .detail-panel.is-map-overlay", styles)
        self.assertIn("max-width: 50%", styles)
        self.assertIn("max-height: 33%", styles)
        self.assertIn("bottom: 12px", styles)
        self.assertIn('"summary media"', styles)
        self.assertIn("opacity: 0.7", styles)
        self.assertIn("font-size: 13px", styles)
        self.assertIn("text-align: right", styles)
        self.assertIn("border-color: transparent", styles)
        self.assertIn("opacity: 0.72", styles)

    def test_ui_version_is_synchronized_for_runtime_and_assets(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        server = (ROOT / "server.py").read_text()

        self.assertIn('href="/styles.css?v=1.0.119"', markup)
        self.assertIn('src="/app.js?v=1.0.119"', markup)
        self.assertIn('>V1.0.119</a>', markup)
        self.assertIn('const UI_VERSION = "V1.0.119"', script)
        self.assertIn('UI_VERSION = "V1.0.119"', server)

    def test_readme_showcases_current_screenshot_and_top_features(self):
        readme = (ROOT / "README.md").read_text()

        self.assertIn("docs/assets/memory-stargraph-ui-2026-07-08.png", readme)
        self.assertTrue((ROOT / "docs" / "assets" / "memory-stargraph-ui-2026-07-08.png").exists())
        features_start = readme.index("## Main Features")
        features_end = readme.index("## GBrain Integration")
        features = readme[features_start:features_end]
        numbered = [line for line in features.splitlines() if line[:2] in {f"{n}." for n in range(1, 10)} or line.startswith("10.")]
        self.assertEqual(len(numbered), 10)
        self.assertTrue(numbered[0].startswith("1. **Ask Yoda**"))
        self.assertIn("2. **Interactive entity graph exploration**", features)
        self.assertIn("3. **Relationship and backlink traversal**", features)
        self.assertIn("4. **Entity mutation from the UI**", features)
        self.assertIn("5. **Media and document attachments**", features)
        self.assertIn("6. **Fast exact-slug and Unicode-aware search**", features)
        self.assertIn("7. **Autopilot memory tour**", features)
        self.assertIn("8. **Local caching**", features)
        self.assertIn("9. **Performance-optimized large graph rendering**", features)
        self.assertIn("10. **Remote/dashboard operation and health checks**", features)
        self.assertIn("The core differentiator", features)
        self.assertIn("AI reasoning paths can be followed and debugged", features)
        self.assertIn("More than a read-only viewer", features)
        self.assertIn("## How Ask Yoda Works", readme)
        self.assertIn("node-scoped chat workflow", readme)
        self.assertIn("gbrain get", readme)
        self.assertIn("graph/backlink queries", readme)
        self.assertIn("falls back to a concise GBrain-context response", readme)
        self.assertIn("does not create durable GBrain notes by itself", readme)
        self.assertNotIn("polish", features.lower())
        self.assertNotIn("ui adjustment", features.lower())

    def test_canvas_hint_adapts_to_pointer_type(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('(hover: hover) and (pointer: fine)', script)
        self.assertIn("Drag to rotate. Hover for full names. Click to select.", script)
        self.assertIn("Drag to rotate. Tap for full names. Long-press a node to select.", script)
        self.assertIn("hover for details, or click a node to select", script)
        self.assertIn("tap for details, or long-press a node to select", script)

    def test_search_normalization_preserves_unicode_terms(self):
        script = (ROOT / "public/app.js").read_text()

        self.assertIn(r"[^\p{L}\p{N}]+", script)
        self.assertIn("toLocaleLowerCase()", script)
        self.assertIn("queryTerms.length > 0", script)
        self.assertNotIn(r"replace(/[^a-z0-9]+/g", script)

    def test_search_prefers_exact_slug_and_reports_elapsed_time(self):
        script = (ROOT / "public/app.js").read_text()
        search_start = script.index("async function runLazySearch")
        search_end = script.index("async function submitSearch", search_start)
        search_block = script[search_start:search_end]

        self.assertIn("function looksLikeExactSlug", script)
        self.assertIn("const searchStartedAt = performance.now()", search_block)
        self.assertLess(search_block.index("await tryExactSlugSearch"), search_block.index('apiGet(`/api/search?q='))
        self.assertIn('apiPost(`/api/entity-expand/${encodeURIComponent(slug)}`)', script)
        self.assertIn('hoverLabel.textContent = `Search completed in ${elapsed}ms`', script)

    def test_console_theme_is_compact_hud_style(self):
        styles = (ROOT / "public" / "styles.css").read_text()
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()

        self.assertIn('href="/styles.css?v=1.0.119"', markup)
        self.assertIn('src="/app.js?v=1.0.119"', markup)
        self.assertIn('V1.0.119', markup)
        self.assertIn('const UI_VERSION = "V1.0.119"', script)
        self.assertIn("--accent: #88f6ff", styles)
        self.assertIn("--accent-3: #ffc66f", styles)
        self.assertIn("radial-gradient(circle at 15% 15%, rgba(136, 246, 255, 0.1)", styles)
        self.assertIn("box-shadow: 0 18px 48px rgba(0, 0, 0, 0.32)", styles)
        self.assertIn("padding: 6px", styles)
        self.assertIn("min-height: 42px", styles)
        self.assertIn("height: 30px", styles)

    def test_console_polish_controls_and_slug_placement(self):
        markup = (ROOT / "public" / "index.html").read_text()
        script = (ROOT / "public/app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()

        self.assertIn('href="/styles.css?v=1.0.119"', markup)
        self.assertIn('src="/app.js?v=1.0.119"', markup)
        self.assertIn('>V1.0.119</a>', markup)
        self.assertIn('const UI_VERSION = "V1.0.119"', script)
        self.assertIn('UI_VERSION = "V1.0.119"', (ROOT / "server.py").read_text())
        self.assertIn('id="selectionSlugAlways"', markup)
        self.assertIn("selectionSlugAlways.textContent = entity.slug", script)
        self.assertIn("selectionSlugAlways.textContent = slug || \"No selection\"", script)
        self.assertIn('aria-label="Run search"', markup)
        self.assertIn('class="search-icon"', markup)
        self.assertNotIn('>Search</button>', markup)
        self.assertIn(".ui-version-link", styles)
        self.assertIn("margin-left: auto", styles)
        self.assertIn("border: 0", styles)
        self.assertIn("background: transparent", styles)
        self.assertIn("async function reopenRelationshipsView(slug)", script)
        self.assertIn('if (action === "remove-link") {\n    return;\n  }', script)
        self.assertIn("modalCancelButton.addEventListener(\"click\"", script)


if __name__ == "__main__":
    unittest.main()
